spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_TLS_ENABLE}

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3-bucket: ${AWS_S3_BUCKET}

ai:
  alan:
    url: ${ALAN_API_URL}
    reset-url: ${ALAN_RESET_URL}
    client-id: ${ALAN_CLIENT_ID}
  openai:
    api-key: ${OPENAI_API_KEY}
    project-id: ${OPENAI_PROJECT_ID}
    org-id: ${OPENAI_ORG_ID}